name: deri
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  google_fonts: ^3.0.1
  page_transition: ^2.0.9
  fluttertoast: ^8.0.9
  path_provider: ^2.0.11
  sqflite: ^2.0.3
  path: ^1.8.1
  date_time_picker: ^2.1.0
  intl: ^0.17.0
  mysql1: ^0.20.0
  readmore: ^2.2.0
  fab_circular_menu: ^1.0.2
  flutter_speed_dial: ^6.0.0
  shared_preferences: ^2.0.15
  flutter_spinkit: ^5.1.0
  flutter_local_notifications: ^9.7.0
  firebase_core: ^1.20.1
  cloud_firestore: ^3.4.4
  firebase_database: ^9.1.1
  firebase_auth: ^3.6.3
  image_picker: ^0.8.5+3
  percent_indicator: ^4.2.2
  firebase_storage: ^10.3.7
  pdf: ^3.8.3
  printing: ^5.9.2
  cached_network_image: ^3.2.1
  rxdart: ^0.27.5
  get: ^4.6.5
  get_storage: ^2.0.3
  flutter_native_timezone: ^2.0.0
  date_picker_timeline: ^1.2.3
  flutter_launcher_icons: ^0.10.0
  firebase_messaging: ^13.0.2
  http: ^0.13.5
  flutter_email_sender: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/1024.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
