// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsuUtfR7H9D3wFrD0P6Izx9mM0L06S3ss',
    appId: '1:940324675493:web:992e77a7d8664440b8924c',
    messagingSenderId: '940324675493',
    projectId: 'deri-f1ee1',
    authDomain: 'deri-f1ee1.firebaseapp.com',
    storageBucket: 'deri-f1ee1.appspot.com',
    measurementId: 'G-X1KTKMYHWW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9p7PyJ0KcapmFlFw2FIst3fV5CF9satc',
    appId: '1:940324675493:android:9fe0c5f865168b24b8924c',
    messagingSenderId: '940324675493',
    projectId: 'deri-f1ee1',
    storageBucket: 'deri-f1ee1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX-_-TEdk9k5hcJpP38naH--u5kRquFGA',
    appId: '1:940324675493:ios:cda0afa120ef2ff9b8924c',
    messagingSenderId: '940324675493',
    projectId: 'deri-f1ee1',
    storageBucket: 'deri-f1ee1.appspot.com',
    iosClientId: '940324675493-9dkc3ju1gv8cospr9sgh0osuqn851pvk.apps.googleusercontent.com',
    iosBundleId: 'com.example.deri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX-_-TEdk9k5hcJpP38naH--u5kRquFGA',
    appId: '1:940324675493:ios:cda0afa120ef2ff9b8924c',
    messagingSenderId: '940324675493',
    projectId: 'deri-f1ee1',
    storageBucket: 'deri-f1ee1.appspot.com',
    iosClientId: '940324675493-9dkc3ju1gv8cospr9sgh0osuqn851pvk.apps.googleusercontent.com',
    iosBundleId: 'com.example.deri',
  );
}
